using System.Text;
using Iced.Intel;
using Sacred.Particles.Reader.Executable;

namespace Sacred.Particles.Reader.Generation;

/// <summary>Version-checked native preview constructor/bone associations.
/// Neither item IDs nor model names are inferred from FX names.</summary>
internal static class ModelFxAttachmentSourceWriter
{
    public static string Write(string executable)
    {
        var image = SacredExecutableImage.Load(executable);
        var code = new NativeCode(image);
        var source = new StringBuilder("// <auto-generated />\n// Sacred.exe equipment FX attachments; regenerate with Sacred.Particles.Reader.\nnamespace Sacred.Particles.Generated;\ninternal static class EmbeddedModelFxAttachments\n{\n    internal static readonly IReadOnlyList<SacredModelFxAttachmentDefinition> Definitions = Array.AsReadOnly<SacredModelFxAttachmentDefinition>([\n");
        Add("Torch", 0x6F41F9, 0x6F313B, null);
        Add("MagicWeapon", 0x6F431B, 0x6F32CD, null);
        Add("Whip", 0x6F4435, 0x6F339F, null);
        Add("Worms", 0x6F454F, 0x6F354B, 0x6F3621);
        Add("ElementalFire", 0x6F466C, 0x6F37C2, 0x6F3893);
        Add("ElementalPoison", 0x6F482D, 0x6F3A45, 0x6F3B21);
        source.AppendLine("    ]);\n}");
        return source.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);

        void Add(string kind, uint constructorCall, uint startPush, uint? endPush)
        {
            var call = code.At(constructorCall);
            if (call.Mnemonic != Mnemonic.Call || call.Op0Kind != OpKind.NearBranch32)
                throw new NotSupportedException("Unmapped model FX constructor call.");
            var start = Bone(startPush);
            var end = endPush is { } address ? $"\"{Bone(address)}\"" : "null";
            source.AppendLine($"        new(0x{call.NearBranch32:X}u, SacredModelEffectKind.{kind}, \"{start}\", {end}, 0x{startPush:X}u),");
        }

        string Bone(uint pushAddress)
        {
            var push = code.At(pushAddress);
            var call = code.At((uint)push.NextIP);
            if (push.Mnemonic != Mnemonic.Push || push.Op0Kind is not (OpKind.Immediate8to32 or OpKind.Immediate32) ||
                call.Mnemonic != Mnemonic.Call || call.NearBranch32 != 0x401000)
                throw new NotSupportedException("Unmapped GRN attachment name lookup.");
            var table = code.At(0x401007);
            if (table.Mnemonic != Mnemonic.Add || table.Op0Register != Register.EAX)
                throw new NotSupportedException("Unmapped GRN attachment name table.");
            var shift = code.At(0x401004);
            if (shift.Mnemonic != Mnemonic.Shl) throw new NotSupportedException("Unmapped attachment name stride.");
            var stride = 1u << checked((int)shift.GetImmediate(1));
            if (stride != SacredExecutableAttachmentNameLayout.SerializedSize)
                throw new NotSupportedException("Unmapped GRN attachment name record layout.");
            return image.String((uint)table.GetImmediate(1) + (uint)push.GetImmediate(0) * stride, (int)stride);
        }
    }
}
