using System.Globalization;
using System.Text;
using Iced.Intel;
using Sacred.Particles.Particles;
using Sacred.Particles.Reader.Evaluation;
using Sacred.Particles.Reader.Executable;

namespace Sacred.Particles.Reader.Generation;

/// <summary>Version-checked extraction of model-only predicates, initializers and draw constants.
/// These systems are also TYPE_FX entries, but their attachment events differ from script presets.</summary>
internal static class ModelEffectSourceWriter
{
    // Balance.bin initializes these named native globals through SpawnWeaponMin
    // and SpawnWeaponMax before item visuals are created. The PE image contains
    // zero-filled storage at the globals themselves.
    private const float SpawnWeaponMinimum = 25.0f;
    private const float SpawnWeaponMaximum = 275.0f;

    public static string Write(string executable)
    {
        var image = SacredExecutableImage.Load(executable);
        var code = new NativeCode(image);
        var source = new StringBuilder("// <auto-generated />\n// Sacred.exe model effects; regenerate with Sacred.Particles.Reader.\nnamespace Sacred.Particles.Generated;\ninternal static class EmbeddedModelEffects\n{\n    internal static readonly IReadOnlyList<SacredModelEffectDefinition> Definitions = Array.AsReadOnly<SacredModelEffectDefinition>([\n");
        Add("Torch", 0x428150, 0x428162, 0x774F37, 0x7752B0, 0x7753C4, 0x7750CF, 0x7750D6);
        Add("Worms", 0x428360, 0x428370, 0x77C535, 0x77C870, 0, 0x77C69B, 0x77C6A0);
        Add("Whip", 0x428190, 0x4281A0, 0x7872E3, 0, 0, 0x7871A1, 0x787185);
        Add("Streak", 0x4282F0, 0x428302, 0x787A73, 0, 0, 0x787841, 0x787825);
        Add("Beam", 0x4283C0, 0x4283D0, 0x401341, 0, 0, 0x5BF78A, 0x5BF78F);
        AddFixedGlowLine();
        source.AppendLine("    ]);");
        source.AppendLine("    internal static readonly IReadOnlyList<SacredModelEffectDefinition> MagicWeaponDefinitions = Array.AsReadOnly<SacredModelEffectDefinition>([");
        var magicFlareTexture = image.String((uint)code.At(0x762EF2).GetImmediate(0), 128);
        var magicFlareColor = Immediate(0x76B5C4);
        for (byte variant = 1; variant <= 5; variant++)
        {
            var magic = EvaluateMagicWeapon(variant);
            var parameters = $"EmbeddedParticleParameters.Read(0, \"{Convert.ToHexStringLower(magic.Emission)}\", \"{Convert.ToHexStringLower(magic.Motion)}\")";
            source.AppendLine($"        new(SacredModelEffectKind.MagicWeapon, Array.Empty<uint>(), 0x5CEA50u, \"{image.String(0x8E7B90, 128)}\", {parameters}.Emission, {parameters}.Motion, 0u, {F(BitConverter.ToSingle(magic.Emission, 8))}, 0, 0f, 0f, 0f, 0f, 0f)");
            source.AppendLine("        {");
            source.AppendLine("            ParticleDrawFlags = 0x9u,");
            source.AppendLine("            ParticleAtlasSide = 1,");
            source.AppendLine($"            LensFlareTextureName = \"{magicFlareTexture}\",");
            source.AppendLine($"            HaloHalfSize = {F(image.Single(0x8907A4) + image.Single(0x890768))},");
            source.AppendLine($"            HaloColor = 0x{magicFlareColor:X8}u,");
            source.AppendLine($"            ParticleColors = Array.AsReadOnly<uint>([{string.Join(", ", magic.Colors.Select(color => $"0x{color:X8}u"))}]),");
            source.AppendLine("        },");
        }
        source.AppendLine("    ]);");
        var standardGlowTexture = image.String((uint)code.At(0x401353).GetImmediate(0), 128);
        source.AppendLine($"    internal static readonly SacredStandardModelEffectDefinition StandardGlow = new(0x5BF3BDu, \"{standardGlowTexture}\", 0x{Immediate(0x5BF433):X8}u, {F(Math.Abs(BitConverter.UInt32BitsToSingle(Immediate(0x5BF438))))}, 10);");
        source.AppendLine($"    internal static readonly SacredElementalWeaponSelectionDefinition ElementalSelection = new({F(image.Single(0x890910))}, {F(SpawnWeaponMinimum)}, {F(SpawnWeaponMaximum)});");
        source.AppendLine("    internal static readonly IReadOnlyList<SacredElementalWeaponEffectDefinition> ElementalDefinitions = Array.AsReadOnly<SacredElementalWeaponEffectDefinition>([");
        AddElemental("Fire", 0x5CE08E, 0x308, 0x77A8E0, 0x77A9C7,
            0x40FF8844, 4, 0, .5f, .5f, image.Single(0x890910));
        AddElemental("Magic", 0x5CE08E, 0, 0, 0,
            0x507033FF, 10, 0, .7f, image.Single(0x890910), image.Single(0x8907C4));
        AddElemental("Poison", 0x5CE08E, 0x328, 0x77C3E0, 0x77C4C6,
            0x4044FF44, 4, 2, .5f, .5f, image.Single(0x890910));
        source.AppendLine("    ]);\n}");
        return source.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);

        void Add(string kind, uint predicate, uint predicateEnd, uint texturePush,
            uint initializer, uint stop, uint colorInstruction, uint sizeInstruction)
        {
            var ids = new List<uint>();
            for (var ip = predicate; ip < predicateEnd;)
            {
                var instruction = code.At(ip);
                if (instruction.Mnemonic == Mnemonic.Cmp && instruction.Op0Register == Register.EAX)
                    ids.Add((uint)instruction.GetImmediate(1));
                ip = (uint)instruction.NextIP;
            }
            if (ids.Count == 0) throw new InvalidDataException("Model effect predicate contains no literal IDs.");
            var texture = image.String((uint)code.At(texturePush).GetImmediate(0), 128);
            var emission = new byte[0x64];
            var motion = new byte[0x20];
            uint particleColor = 0;
            if (initializer != 0)
            {
                var memory = new PresetMemory(image, 0x2660, SacredParticleQuality.High);
                var machine = new X86Machine(code, memory);
                var obj = memory.BaseAddress;
                var stack = obj + 0x1F000;
                var sentinel = obj + 0x1FF00;
                memory.Write(obj + 0x68, 4, obj + 0x8000);
                memory.Write(obj + 0x6C, 4, obj + 0x8000);
                memory.Write(obj + 0xAC, 4, 0); // Sound owner; no effect on particle parameters.
                memory.Write(stack, 4, sentinel);
                memory.Write(stack + 4, 4, obj + 0x10000);
                machine.Registers.Set(Register.ESP, stack);
                machine.Registers.Set(Register.ECX, obj);
                machine.Run(initializer, stop == 0 ? sentinel : stop, default);
                if (memory.ReadUninitializedObject || !memory.IsWritten(0x20BC, 0x84))
                    throw new InvalidDataException("Incomplete model particle initialization.");
                emission = memory.ObjectBytes(0x20DC, 0x64).ToArray();
                motion = memory.ObjectBytes(0x20BC, 0x20).ToArray();
                particleColor = BitConverter.ToUInt32(memory.ObjectBytes(0x20AC, 4));
            }
            var color = Immediate(colorInstruction);
            var halfSize = Math.Abs(BitConverter.UInt32BitsToSingle(Immediate(sizeInstruction)));
            var chain = kind is "Whip" or "Streak";
            var count = chain ? (int)Immediate(kind == "Whip" ? 0x787164u : 0x787804u) : 0;
            var link = chain ? image.Single(kind == "Whip" ? 0x8909A8u : 0x89090Cu) : 0;
            var inertia = chain ? BitConverter.UInt32BitsToSingle(Immediate(kind == "Whip" ? 0x7872E8u : 0x787A78u)) * image.Single(0x890C60) : 0;
            source.AppendLine($"        new(SacredModelEffectKind.{kind}, Array.AsReadOnly<uint>([{string.Join(", ", ids.Select(id => id + "u"))}]), 0x{predicate:X}u, \"{texture}\", EmbeddedParticleParameters.Read(0, \"{Convert.ToHexStringLower(emission)}\", \"{Convert.ToHexStringLower(motion)}\").Emission, EmbeddedParticleParameters.Read(0, \"{Convert.ToHexStringLower(emission)}\", \"{Convert.ToHexStringLower(motion)}\").Motion, 0x{color:X8}u, {F(halfSize)}, {count}, {F(link)}, {F(inertia)}, {F(kind == "Streak" ? BitConverter.UInt32BitsToSingle(Immediate(0x787C65)) : 0)}, {F(kind == "Streak" ? image.Single(0x8980B8) : 0)}, {F(kind == "Streak" ? image.Single(0x8980BC) : 0)})");
            source.AppendLine("        {");
            // Confirm the native base-record operand instead of inferring inheritance from resource names.
            var usesBaseItem = false;
            for (var ip = predicate; ip < predicate + 0x70;)
            {
                var instruction = code.At(ip);
                if (instruction.MemoryBase == Register.EAX && instruction.MemoryDisplacement64 == 0x24)
                    usesBaseItem = true;
                ip = (uint)instruction.NextIP;
                if (instruction.Mnemonic == Mnemonic.Ret && kind == "Torch") break;
            }
            source.AppendLine($"            UsesBaseItem = {usesBaseItem.ToString().ToLowerInvariant()},");
            source.AppendLine($"            ParticleColor = 0x{particleColor:X8}u,");
            if (kind is "Torch" or "Worms")
            {
                source.AppendLine($"            ParticleAtlasSide = {Immediate(kind == "Torch" ? 0x7750AAu : 0x77C648u)},");
                source.AppendLine($"            ParticleDrawFlags = 0x{Immediate(kind == "Torch" ? 0x7750ADu : 0x77C64Bu):X}u,");
            }
            // Torch draw 7750D4 passes stdLensflare type 3. The executable analysis
            // names that callee, whose type switch resolves 3 to this texture.
            if (kind == "Torch")
                source.AppendLine("            LensFlareTextureName = \"PARTICLE_GLOW01.TGA\",");
            if (chain)
            {
                uint[] corners = kind == "Whip" ? [0x7871A1, 0x7871EC, 0x78723B, 0x787287] : [0x787841, 0x78788B, 0x7878D5, 0x78791F];
                source.AppendLine($"            CornerColors = Array.AsReadOnly<uint>([{string.Join(", ", corners.Select(a => $"0x{Immediate(a):X8}u"))}]),");
            }
            if (kind == "Streak")
            {
                source.AppendLine($"            HaloHalfSize = {F(Math.Abs(BitConverter.UInt32BitsToSingle(Immediate(0x787950))))},");
                source.AppendLine($"            HaloCornerColors = Array.AsReadOnly<uint>([{string.Join(", ", new uint[] { 0x78796C, 0x787988, 0x7879F6, 0x787A19 }.Select(a => $"0x{Immediate(a):X8}u"))}]),");
            }
            if (kind == "Beam")
                source.AppendLine($"            BeamDensity = {F(BitConverter.UInt32BitsToSingle(Immediate(0x5BF765)))}, HaloDensity = {F(BitConverter.UInt32BitsToSingle(Immediate(0x5BF7B6)))}, HaloColor = 0x{Immediate(0x5BF7D9):X8}u, HaloHalfSize = {F(BitConverter.UInt32BitsToSingle(Immediate(0x5BF7DE)))},");
            if (kind == "Worms")
                source.AppendLine($"            BeamDensity = {F(BitConverter.UInt32BitsToSingle(Immediate(0x77C66A)))},");
            source.AppendLine("        },");
        }

        void AddFixedGlowLine()
        {
            var itemId = (uint)code.At(0x5BF47B).GetImmediate(1);
            var texture = image.String((uint)code.At(0x401341).GetImmediate(0), 128);
            var zeroEmission = new byte[SacredParticleEmissionLayout.SerializedSize];
            var zeroMotion = new byte[SacredParticleMotionLayout.SerializedSize];
            var parameters = $"EmbeddedParticleParameters.Read(0, \"{Convert.ToHexStringLower(zeroEmission)}\", \"{Convert.ToHexStringLower(zeroMotion)}\")";
            source.AppendLine($"        new(SacredModelEffectKind.Beam, Array.AsReadOnly<uint>([{itemId}u]), 0x5BF47Bu, \"{texture}\", {parameters}.Emission, {parameters}.Motion, 0x{Immediate(0x5BF4F5):X8}u, {F(BitConverter.UInt32BitsToSingle(Immediate(0x5BF4FA)))}, 0, 0f, 0f, 0f, 0f, 0f)");
            source.AppendLine("        {");
            source.AppendLine("            UsesBaseItem = false,");
            source.AppendLine($"            BeamDensity = {F(BitConverter.UInt32BitsToSingle(Immediate(0x5BF4D0)))},");
            source.AppendLine("        },");
        }

        void AddElemental(string kind, uint nativeAddress, uint particleTypeId,
            uint initializer, uint stop, uint glowColor, float glowScale,
            float glowOffset, float glowDensity, float lowScale, float highScale)
        {
            var zeroEmission = new byte[SacredParticleEmissionLayout.SerializedSize];
            var zeroMotion = new byte[SacredParticleMotionLayout.SerializedSize];
            var emission = zeroEmission;
            var motion = zeroMotion;
            uint particleColor = 0;
            float emissionSizeScale = 0;
            float sizeChangeScale = 0;
            if (initializer != 0)
            {
                var atZero = EvaluateElemental(initializer, stop, 0);
                var atOne = EvaluateElemental(initializer, stop, 1000);
                emission = atZero.Emission;
                motion = atZero.Motion;
                particleColor = atZero.Color;
                emissionSizeScale = BitConverter.ToSingle(atOne.Emission, 8) - BitConverter.ToSingle(emission, 8);
                sizeChangeScale = BitConverter.ToSingle(atOne.Motion, 8) - BitConverter.ToSingle(motion, 8);
            }
            var texture = image.String(0x8E7B90, 128);
            var parameters = $"EmbeddedParticleParameters.Read(0, \"{Convert.ToHexStringLower(emission)}\", \"{Convert.ToHexStringLower(motion)}\")";
            source.AppendLine($"        new(SacredElementalWeaponEffectKind.{kind}, 0x{nativeAddress:X}u, 0x{particleTypeId:X}u, \"{texture}\", {parameters}.Emission, {parameters}.Motion, 0x{particleColor:X8}u, 0x3u, 1, 0x{glowColor:X8}u, {F(glowScale)}, {F(glowOffset)}, {F(glowDensity)}, {F(lowScale)}, {F(highScale)}, {F(emissionSizeScale)}, {F(sizeChangeScale)}),");
        }

        (byte[] Emission, byte[] Motion, uint Color) EvaluateElemental(
            uint initializer, uint stop, uint eventIntensity)
        {
            var memory = new PresetMemory(image, 0x2660, SacredParticleQuality.High);
            var machine = new X86Machine(code, memory);
            var obj = memory.BaseAddress;
            var stack = obj + 0x1F000;
            var sentinel = obj + 0x1FF00;
            var effectEvent = obj + 0x10000;
            memory.Write(obj + 0x68, 4, obj + 0x8000);
            memory.Write(obj + 0x6C, 4, obj + 0x8000);
            memory.Write(effectEvent + 0x3C, 4, eventIntensity);
            memory.Write(stack, 4, sentinel);
            memory.Write(stack + 4, 4, effectEvent);
            machine.Registers.Set(Register.ESP, stack);
            machine.Registers.Set(Register.ECX, obj);
            machine.Run(initializer, stop, default);
            if (!memory.IsWritten(0x20BC, 0x84))
                throw new InvalidDataException("Incomplete elemental weapon particle initialization.");
            return (memory.ObjectBytes(0x20DC, 0x64).ToArray(),
                memory.ObjectBytes(0x20BC, 0x20).ToArray(),
                BitConverter.ToUInt32(memory.ObjectBytes(0x20AC, 4)));
        }

        (byte[] Emission, byte[] Motion, uint[] Colors) EvaluateMagicWeapon(byte variant)
        {
            var memory = new PresetMemory(image, 0x2660, SacredParticleQuality.High);
            var machine = new X86Machine(code, memory);
            var obj = memory.BaseAddress;
            var stack = obj + 0x1F000;
            var sentinel = obj + 0x1FF00;
            var effectEvent = obj + 0x10000;
            memory.Write(obj + 0x68, 4, obj + 0x8000);
            memory.Write(obj + 0x6C, 4, obj + 0x8000);
            memory.Write(effectEvent + 0x3C, 4, variant);
            memory.Write(stack, 4, sentinel);
            memory.Write(stack + 4, 4, effectEvent);
            machine.Registers.Set(Register.ESP, stack);
            machine.Registers.Set(Register.ECX, obj);
            machine.Run(0x76B5F0, sentinel, default);
            if (!memory.IsWritten(0x20A4, 0x400) || !memory.IsWritten(0x24B0, 0x84))
                throw new InvalidDataException("Incomplete magic-weapon particle initialization.");
            var colorBytes = memory.ObjectBytes(0x20A4, 0x400);
            var colors = new uint[256];
            for (var index = 0; index < colors.Length; index++)
                colors[index] = BitConverter.ToUInt32(colorBytes.Slice(index * 4, 4));
            return (memory.ObjectBytes(0x24D0, 0x64).ToArray(),
                memory.ObjectBytes(0x24B0, 0x20).ToArray(), colors);
        }

        uint Immediate(uint address)
        {
            var instruction = code.At(address);
            return (uint)instruction.GetImmediate(instruction.Mnemonic == Mnemonic.Push ? 0 : 1);
        }
    }

    private static string F(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "f";
}
