using System.Globalization;
using System.Runtime.InteropServices;
using System.Text;

namespace Sacred.Particles.Reader.Generation;

internal static class ParticleCatalogueSourceWriter
{
    public static string Write(SacredParticleCatalogue catalogue)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// Generated from Sacred.exe by Sacred.Particles.Reader. Regenerate; do not edit IDs or parameters.");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Sacred.Particles.Generated;");
        source.AppendLine($"internal static partial class EmbeddedParticleCatalogue{catalogue.Quality}");
        source.AppendLine("{");
        source.AppendLine("    static partial void Populate(ref SacredParticleCatalogue? catalogue)");
        source.AppendLine("    {");
        source.AppendLine($"        catalogue = new({CSharpLiteral.String(catalogue.ExecutableSha256)}, {CSharpLiteral.String(catalogue.NativeCodeSha256)}, SacredParticleQuality.{catalogue.Quality}, {catalogue.WorldUnitsPerTile.ToString("R", CultureInfo.InvariantCulture)}f,");
        source.AppendLine("        [");
        foreach (var entry in catalogue.Definitions.OrderBy(d => d.TypeId))
        {
            var bindings = ReadOnlyArray("SacredParticleTextureBinding", entry.TextureBindings.Select(b =>
                $"new({CSharpLiteral.UInt32(b.NativeHandleOffset)}, {CSharpLiteral.String(b.TextureName)})"));
            var draw = entry.Draw is { } d
                ? $"new SacredParticleDrawDefinition({CSharpLiteral.String(d.TextureName)}, {CSharpLiteral.UInt32(d.RawFlags)}, {CSharpLiteral.UInt32(d.NativeAddress)}) {{ AtlasSide = {d.AtlasSide} }}" : "null";
            var parameters = ReadOnlyArray("SacredParticleParameterSet", entry.ParameterSets.Select(p =>
                $"EmbeddedParticleParameters.Read({p.Index}, \"{Hex(p.Emission)}\", \"{Hex(p.Motion)}\") with {{ Colors = EmbeddedParticleParameters.ReadColors(\"{Convert.ToHexStringLower(MemoryMarshal.AsBytes(p.Colors.ToArray().AsSpan()))}\") }}"));
            source.AppendLine($"            new({CSharpLiteral.UInt32(entry.TypeId)}, {CSharpLiteral.String(entry.TypeName)}, {CSharpLiteral.UInt32(entry.TypeRecordAddress)}, {CSharpLiteral.UInt32(entry.FactoryAddress)}, {CSharpLiteral.String(entry.NativeClass)}, {CSharpLiteral.Int32(entry.Preset)}, SacredParticleDefinitionStatus.{entry.Status}, {CSharpLiteral.String(entry.Diagnostic)}, {bindings}, {draw}, {parameters}) {{ EmissionMode = {entry.EmissionMode}, UsesWind = {(entry.UsesWind ? "true" : "false")} }},");
        }
        var projection = catalogue.Projection;
        source.AppendLine("        ])");
        source.AppendLine($"        {{ Projection = new({Float(projection.HorizontalScale)}, {Float(projection.VerticalScale)}, {Float(projection.GroundDepthFactor)}, {Float(projection.HeightFactor)}, {Float(projection.DefaultWind)}) }};");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static string ReadOnlyArray(string elementType, IEnumerable<string> values)
    {
        var array = values.ToArray();
        return array.Length == 0 ? $"Array.Empty<{elementType}>()"
            : $"Array.AsReadOnly<{elementType}>([{string.Join(", ", array)}])";
    }

    private static string Hex<T>(T value) where T : unmanaged =>
        Convert.ToHexStringLower(MemoryMarshal.AsBytes(MemoryMarshal.CreateReadOnlySpan(ref value, 1)));

    private static string Float(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "f";
}
