using System.Globalization;
using System.Runtime.InteropServices;
using System.Text;

namespace Sacred.Particles.Reader.Generation;

internal static class ParticleCatalogueSourceWriter
{
    public static string Write(SacredParticleCatalogue catalogue)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// Generated from Sacred.exe by Sacred.Particles.Reader. Regenerate; do not edit IDs or parameters.");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Sacred.Particles.Generated;");
        source.AppendLine($"internal static partial class EmbeddedParticleCatalogue{catalogue.Quality}");
        source.AppendLine("{");
        source.AppendLine("    static partial void Populate(ref SacredParticleCatalogue? catalogue)");
        source.AppendLine("    {");
        source.AppendLine($"        catalogue = new({CSharpLiteral.String(catalogue.ExecutableSha256)}, {CSharpLiteral.String(catalogue.NativeCodeSha256)}, SacredParticleQuality.{catalogue.Quality}, {catalogue.WorldUnitsPerTile.ToString("R", CultureInfo.InvariantCulture)}f,");
        source.AppendLine("        [");
        void Entries(IEnumerable<SacredParticleDefinition> entries)
        {
            foreach (var entry in entries.OrderBy(d => d.TypeId).ThenBy(d => d.Preset))
            {
                var bindings = ReadOnlyArray("SacredParticleTextureBinding", entry.TextureBindings.Select(b =>
                    $"new({CSharpLiteral.UInt32(b.NativeHandleOffset)}, {CSharpLiteral.String(b.TextureName)})"));
                var draw = entry.Draw is { } d
                    ? $"new SacredParticleDrawDefinition({CSharpLiteral.String(d.TextureName)}, {CSharpLiteral.UInt32(d.RawFlags)}, {CSharpLiteral.UInt32(d.NativeAddress)}) {{ AtlasSide = {d.AtlasSide} }}" : "null";
                var parameters = ReadOnlyArray("SacredParticleParameterSet", entry.ParameterSets.Select(p =>
                    $"EmbeddedParticleParameters.Read({p.Index}, \"{Hex(p.Emission)}\", \"{Hex(p.Motion)}\") with {{ Colors = EmbeddedParticleParameters.ReadColors(\"{Convert.ToHexStringLower(MemoryMarshal.AsBytes(p.Colors.ToArray().AsSpan()))}\") }}"));
                var halo = entry.Halo is { } h
                    ? $", Halo = new({CSharpLiteral.String(h.TextureName)}, {Float(h.HalfSize)}, {CSharpLiteral.UInt32(h.Color)}, {CSharpLiteral.UInt32(h.NativeAddress)})" : string.Empty;
                var particles = entry.InitialParticles.Count == 0 ? string.Empty :
                    $", InitialParticles = EmbeddedParticleParameters.ReadParticles(\"{Convert.ToHexStringLower(MemoryMarshal.AsBytes(entry.InitialParticles.ToArray().AsSpan()))}\")";
                source.AppendLine($"            new({CSharpLiteral.UInt32(entry.TypeId)}, {CSharpLiteral.String(entry.TypeName)}, {CSharpLiteral.UInt32(entry.TypeRecordAddress)}, {CSharpLiteral.UInt32(entry.FactoryAddress)}, {CSharpLiteral.String(entry.NativeClass)}, {CSharpLiteral.Int32(entry.Preset)}, SacredParticleDefinitionStatus.{entry.Status}, {CSharpLiteral.String(entry.Diagnostic)}, {bindings}, {draw}, {parameters}) {{ DisplayName = {CSharpLiteral.String(entry.DisplayName)}, EmissionMode = {entry.EmissionMode}, UsesWind = {(entry.UsesWind ? "true" : "false")}, EmitBeforeMovement = {(entry.EmitBeforeMovement ? "true" : "false")}, Capacity = {entry.Capacity}, GroundCollision = ParticleGroundCollision.{entry.GroundCollision}, ModelBurstCount = {entry.ModelBurstCount}, IsEventPreset = {(entry.IsEventPreset ? "true" : "false")}, OneTime = {(entry.OneTime ? "true" : "false")}{particles}{halo} }},");
            }
        }
        Entries(catalogue.Definitions);
        source.AppendLine("        ],");
        source.AppendLine("        [");
        Entries(catalogue.EventDefinitions);
        var projection = catalogue.Projection;
        source.AppendLine("        ])");
        source.AppendLine($"        {{ Projection = new({Float(projection.HorizontalScale)}, {Float(projection.VerticalScale)}, {Float(projection.GroundDepthFactor)}, {Float(projection.HeightFactor)}, {Float(projection.DefaultWind)}) }};");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static string ReadOnlyArray(string elementType, IEnumerable<string> values)
    {
        var array = values.ToArray();
        return array.Length == 0 ? $"Array.Empty<{elementType}>()"
            : $"Array.AsReadOnly<{elementType}>([{string.Join(", ", array)}])";
    }

    private static string Hex<T>(T value) where T : unmanaged =>
        Convert.ToHexStringLower(MemoryMarshal.AsBytes(MemoryMarshal.CreateReadOnlySpan(ref value, 1)));

    private static string Float(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "f";
}
