<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Raffinert.EmbeddedResourceAccessGenerator" Version="1.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>build; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="10.0.11" />
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.Dxc" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sacred.Core\Sacred.Core.csproj" />
    <ProjectReference Include="..\Sacred.Assets\Sacred.Assets.csproj" />
    <ProjectReference Include="..\Sacred.Granny\Sacred.Granny.csproj" />
    <ProjectReference Include="..\Sacred.Particles\Sacred.Particles.csproj" />
    <ProjectReference Include="..\Sacred.Shaders\Sacred.Shaders.csproj" />
    <ProjectReference Include="..\Sacred.Inventory\Sacred.Inventory.csproj" />
    <ProjectReference Include="..\Sacred.World\Sacred.World.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Embeds\*.tga" />
  </ItemGroup>
</Project>
