"""Write focused native disassembly supporting the mapped binary fields."""
import argparse
from pathlib import Path
from native_image import NativeImage

# Virtual addresses in the verified unpacked image. Each range starts on an instruction.
RANGES = {
    'native reference orthographic volume': (0x6282C9, 0x6282F1),
    'native reference camera eye': (0x811700, 0x81173F),
    'native environment default wind': (0x418F80, 0x418F94),
    'smoke wind and emission selection': (0x76E2D0, 0x76E3E6),
    'dwarf magic update order': (0x78A360, 0x78A3AA),
    'parameter selection probabilities': (0x7687F0, 0x7688D7),
    'packed RGBA fade table generation': (0x763F50, 0x7640B4),
    'billboard size projection and fade color lookup': (0x7620FF, 0x762352),
    'particle blend flags': (0x761B9B, 0x761BCD),
    'two-slot blend override': (0x761F87, 0x76200E),
    'native blend state enabling': (0x6434FF, 0x643531),
    'spawn random position and velocity half-ranges': (0x765590, 0x765770),
    'timed birth catch-up': (0x7659B3, 0x765AA8),
    'instruction prefix reader': (0x45f220, 0x45f298),
    'literal type and signed short height decoders': (0x473a27, 0x473aa3),
    'precise coordinate decoder': (0x474065, 0x4740a2),
    'symbolic tile operand check': (0x474181, 0x4741a8),
    'literal tile coordinate decoder': (0x474703, 0x474740),
    'creation height and position operands': (0x486186, 0x486218),
    'effect precise position and height transform': (0x489003, 0x489077),
    'smoke factory allocation and constructor': (0x5a0ccf, 0x5a0d07),
    'dwarf magic factory allocation and constructor': (0x5a17df, 0x5a1817),
    'smoke constructor and named texture lookups': (0x76e200, 0x76e2c4),
    'smoke serialization framing': (0x76e7d0, 0x76e83b),
    'smoke preset entry and switch': (0x76e980, 0x76e9b9),
    'smoke draw-pass texture selection': (0x76e600, 0x76e7a8),
    'motion update': (0x764113, 0x7642c1),
    'spawn variant and burst count': (0x764dc2, 0x764e17),
    'emission interval and elapsed time': (0x76539a, 0x7653d3),
    'dwarf magic constructor and named texture lookup': (0x78a2d0, 0x78a343),
    'dwarf magic serialization framing': (0x78a420, 0x78a47d),
    'blue dwarf magic preset': (0x78a5d0, 0x78a72c),
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--memory-image', required=True)
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    image = NativeImage(args.memory_image)
    lines = ['# Native particle evidence', '', f'Unpacked .text SHA-256: `{image.text_hash}`.', '',
             'Virtual addresses, image base 0x400000. Generated by native_evidence.py.', '']
    for title, (start, end) in RANGES.items():
        lines.extend([f'## {title}', '', '```asm', *image.disassembly(start, end), '```', ''])
    Path(args.output).write_text('\n'.join(lines), encoding='utf-8')


if __name__ == '__main__':
    main()
