<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sacred.Core\Sacred.Core.csproj" />
    <ProjectReference Include="..\Sacred.Granny\Sacred.Granny.csproj" />
  </ItemGroup>
</Project>
