using System.Globalization;
using System.Text;
using System.Text.Json;

namespace ParticleResearch;

internal sealed record EffectCandidate(double TileDistance, ScriptEffect Effect);
internal sealed record SampleMatch(string ObservationId, string SceneId, string FixtureStatus,
    int FixtureX, int FixtureY, EffectCandidate[] Candidates);

internal static class SampleMatcher
{
    public static List<SampleMatch> Match(string samples, ScriptEffect[] effects)
    {
        var result = new List<SampleMatch>();
        foreach (var line in File.ReadLines(Path.Combine(samples, "emitters.compact.jsonl")))
        {
            using var json = JsonDocument.Parse(line);
            var sample = json.RootElement;
            var fixture = sample.GetProperty("fixture_match");
            var xy = fixture.GetProperty("world_tile_xy");
            var x = xy[0].GetInt32();
            var y = xy[1].GetInt32();
            var ordered = effects.Where(e => e.Creation.TilePosition.HasValue)
                .Select(e => new EffectCandidate(Distance(e, x, y), e))
                .OrderBy(e => e.TileDistance).ThenBy(e => e.Effect.Offset).ToArray();
            if (ordered.Length == 0) throw new InvalidDataException("Selected script contains no literal FX positions.");
            var nearby = ordered.TakeWhile(e => e.TileDistance <= 5).ToArray();
            result.Add(new SampleMatch(sample.GetProperty("observation_id").GetString()!,
                sample.GetProperty("scene_id").GetString()!, fixture.GetProperty("status").GetString()!,
                x, y, nearby.Length == 0 ? ordered.Take(3).ToArray() : nearby));
        }
        return result;
    }

    private static double Distance(ScriptEffect effect, int x, int y)
    {
        var tile = effect.Creation.TilePosition!.Value;
        var dx = (double)tile.X - x;
        var dy = (double)tile.Y - y;
        return Math.Sqrt(dx * dx + dy * dy);
    }

    public static void WriteMarkdown(string path, string script, List<SampleMatch> matches)
    {
        var text = new StringBuilder($"# Script matches for the particle samples\n\nSource: `{script}`. Generated by ParticleResearch.\n\n");
        text.AppendLine("Nearest by fixture tile XY; these are spatial candidates, not proven fixture ownership. Fissure observations retain their original provisional status.\n");
        text.AppendLine("| Observation | Fixture tile | Nearest script effect | Script tile | Height | Distance (tiles) | Command offset |\n| --- | --- | --- | --- | ---: | ---: | ---: |");
        foreach (var match in matches)
        {
            var candidate = match.Candidates[0];
            var creation = candidate.Effect.Creation;
            var tile = creation.TilePosition!.Value;
            text.AppendLine(CultureInfo.InvariantCulture,
                $"| {match.ObservationId} | {match.FixtureX},{match.FixtureY} | {candidate.Effect.TypeName} | {tile.X},{tile.Y} | {creation.HeightOffset} | {candidate.TileDistance:F2} | 0x{candidate.Effect.Offset:X} |");
        }
        File.WriteAllText(path, text.ToString());
    }
}
