using System.Globalization;
using System.Text;

namespace Sacred.Core.Analyzer;

internal sealed class MarkdownReportWriter(
    IReadOnlyList<GameFileDefinition> definitions,
    IReadOnlyDictionary<string, LayoutCoverage> layouts,
    IReadOnlyList<DiscoveredGameFile> discoveredFiles)
{
    public string Write()
    {
        var output = new StringBuilder();
        output.AppendLine("# Sacred game-file format coverage");
        output.AppendLine();
        output.AppendLine("> Generated by `Sacred.Core.Analyzer`. Edit layout types or the analyzer catalog, then regenerate this file; do not hand-edit coverage values.");
        output.AppendLine();
        WriteMethod(output);
        WriteSummary(output);
        WriteAnalyzedFiles(output);
        WriteFileStructures(output);
        WriteLayoutsByNamespace(output);
        WriteMissingLayouts(output);
        WriteUncataloguedFiles(output);
        return output.ToString();
    }

    private static void WriteMethod(StringBuilder output)
    {
        output.AppendLine("## How coverage is calculated");
        output.AppendLine();
        output.AppendLine("Byte coverage is the percentage of bytes covered by those fields. Overlapping serialized fields are rejected by the analyzer. Fixed-width strings use `BinaryString` metadata so the report treats the whole encoded range as one field.");
        output.AppendLine();
        output.AppendLine("Percentages describe the fixed-size structures represented in `Sacred.Core`; repetitions are not weighted by one particular game installation. Variable-size image, sound, Granny, compressed, and string payloads are excluded where their internal byte layout is not a fixed `StructLayout` type.");
        output.AppendLine();
    }

    private void WriteSummary(StringBuilder output)
    {
        var uniqueLayouts = layouts.Values.ToArray();
        var knownFields = uniqueLayouts.Sum(static layout => layout.KnownFieldCount);
        var totalFields = uniqueLayouts.Sum(static layout => layout.Fields.Count);
        var knownBytes = uniqueLayouts.Sum(static layout => layout.KnownByteCount);
        var totalBytes = uniqueLayouts.Sum(static layout => layout.Size);
        var mappedFormats = definitions.Count(static definition => definition.Sections.Count > 0);
        var missingFormats = definitions.Count - mappedFormats;

        output.AppendLine("## Summary");
        output.AppendLine();
        output.AppendLine("| Metric | Coverage |");
        output.AppendLine("|---|---:|");
        output.AppendLine($"| Catalogued game-file patterns | {definitions.Count} |");
        output.AppendLine($"| Patterns with layout classes | {mappedFormats} |");
        output.AppendLine($"| Patterns missing layout classes | {missingFormats} |");
        output.AppendLine($"| Unique `StructLayout` types | {uniqueLayouts.Length} |");
        output.AppendLine($"| Analyzed fields | {knownFields}/{totalFields} ({Percent(knownFields, totalFields)}) |");
        output.AppendLine($"| Analyzed fixed-layout bytes | {knownBytes}/{totalBytes} ({Percent(knownBytes, totalBytes)}) |");
        output.AppendLine($"| Matching files found in the scanned installation | {CountMappedDiscoveredFiles()} |");
        output.AppendLine();
    }

    private void WriteAnalyzedFiles(StringBuilder output)
    {
        output.AppendLine("## Analyzed game files");
        output.AppendLine();
        output.AppendLine("| Game file | Installed files checked | Layout sections | Section byte coverage |");
        output.AppendLine("|---|---:|---|---|");
        foreach (var definition in definitions.Where(static definition => definition.Sections.Count > 0))
        {
            output.Append("| `").Append(definition.PathPattern).Append("` | ")
                .Append(ObservedSummary(definition)).Append(" | ")
                .Append(string.Join(" → ", definition.Sections.Select(static section => Escape(section.Name))))
                .Append(" | ").Append(string.Join("<br>", definition.Sections.Select(section =>
                {
                    var layout = layouts[section.LayoutTypeName];
                    return $"**{Escape(section.Name)}:** {layout.KnownByteCount}/{layout.Size} ({Percent(layout.KnownByteCount, layout.Size)})";
                }))).AppendLine(" |");
        }
        output.AppendLine();
    }

    private void WriteFileStructures(StringBuilder output)
    {
        output.AppendLine("## File structures");
        output.AppendLine();
        foreach (var definition in definitions.Where(static definition => definition.Sections.Count > 0))
        {
            output.Append("### `").Append(definition.PathPattern).AppendLine("`");
            output.AppendLine();
            output.AppendLine(definition.Description + ".");
            output.AppendLine();
            foreach (var section in definition.Sections)
            {
                var coverage = layouts[section.LayoutTypeName];
                output.Append("- ").Append(Escape(section.Name)).Append(": [`")
                    .Append(coverage.TypeName).Append("`](#")
                    .Append(Anchor(coverage)).Append(") — ")
                    .Append(section.Repetition).Append(", 0x")
                    .Append(coverage.Size.ToString("X", CultureInfo.InvariantCulture)).Append(" bytes");
                if (section.Notes is not null)
                    output.Append(". ").Append(section.Notes);
                output.AppendLine();
            }
            output.AppendLine();
        }
    }

    private void WriteLayoutsByNamespace(StringBuilder output)
    {
        output.AppendLine("## Layouts by namespace");
        output.AppendLine();
        foreach (var namespaceGroup in layouts.Values
                     .OrderBy(static layout => layout.Namespace, StringComparer.Ordinal)
                     .ThenBy(static layout => layout.TypeName, StringComparer.Ordinal)
                     .GroupBy(static layout => layout.Namespace))
        {
            output.Append("### `").Append(namespaceGroup.Key).AppendLine("`");
            output.AppendLine();
            foreach (var layout in namespaceGroup)
                WriteLayout(output, layout);
        }
    }

    private static void WriteLayout(StringBuilder output, LayoutCoverage layout)
    {
        output.Append("#### `").Append(layout.TypeName).AppendLine("`");
        output.AppendLine();
        output.AppendLine(layout.Documentation);
        output.AppendLine();
        output.Append("Size: **0x").Append(layout.Size.ToString("X", CultureInfo.InvariantCulture))
            .Append("** bytes. Fields: **").Append(layout.KnownFieldCount).Append('/').Append(layout.Fields.Count)
            .Append(" (" + Percent(layout.KnownFieldCount, layout.Fields.Count)).Append(")**. Bytes: **")
            .Append(layout.KnownByteCount).Append('/').Append(layout.Size)
            .Append(" (" + Percent(layout.KnownByteCount, layout.Size)).AppendLine(")**.");
        output.AppendLine();
        output.AppendLine("| Offset | Bytes | Serialized type | Field | Status | Documentation |");
        output.AppendLine("|---:|---:|---|---|---|---|");
        foreach (var field in layout.Fields)
        {
            output.Append("| 0x").Append(field.Offset.ToString("X", CultureInfo.InvariantCulture))
                .Append(" | ").Append(field.Size)
                .Append(" | `").Append(Escape(field.TypeName)).Append("` | `")
                .Append(Escape(field.Name)).Append("` | ")
                .Append(field.IsKnown ? "Known" : "Unknown")
                .Append(" | ").Append(Escape(field.Documentation)).AppendLine(" |");
        }
        if (layout.Fields.Count == 0)
            output.AppendLine("| — | — | — | — | Unknown | No fields have been mapped. |");
        output.AppendLine();
        output.Append("Unknown byte ranges: ").AppendLine(FormatRanges(layout.UnknownRanges));
        output.AppendLine();
    }

    private void WriteMissingLayouts(StringBuilder output)
    {
        output.AppendLine("## Missing layout classes");
        output.AppendLine();
        output.AppendLine("These catalogued formats were found in the game or are adjacent to the formats currently consumed by the repository, but no `Sacred.Core` `StructLayout` class maps them yet.");
        output.AppendLine();
        output.AppendLine("| Game file | Purpose | Installed files checked |");
        output.AppendLine("|---|---|---:|");
        foreach (var definition in definitions.Where(static definition => definition.Sections.Count == 0))
        {
            output.Append("| `").Append(definition.PathPattern).Append("` | ")
                .Append(Escape(definition.Description)).Append(" | ")
                .Append(ObservedSummary(definition)).AppendLine(" |");
        }
        output.AppendLine();
    }

    private void WriteUncataloguedFiles(StringBuilder output)
    {
        var uncatalogued = discoveredFiles
            .Where(file => definitions.All(definition => !GameFileScanner.Matches(definition.PathPattern, file.RelativePath)))
            .ToArray();
        output.AppendLine("## Observed files outside the catalog");
        output.AppendLine();
        if (discoveredFiles.Count == 0)
        {
            output.AppendLine("No game directory was scanned for this generated report.");
        }
        else if (uncatalogued.Length == 0)
        {
            output.AppendLine("Every scanned `.pak`, `.bin`, `.keyx`, `.wldx`, `.tmp`, and localized `global.res` file matched a catalog entry.");
        }
        else
        {
            foreach (var file in uncatalogued)
                output.Append("- `").Append(file.RelativePath).Append("` (").Append(FormatBytes(file.Length)).AppendLine(")");
        }
        output.AppendLine();
    }

    private int CountMappedDiscoveredFiles() => discoveredFiles.Count(file => definitions.Any(definition =>
        definition.Sections.Count > 0 && GameFileScanner.Matches(definition.PathPattern, file.RelativePath)));

    private string ObservedSummary(GameFileDefinition definition)
    {
        var matches = discoveredFiles.Where(file => GameFileScanner.Matches(definition.PathPattern, file.RelativePath)).ToArray();
        if (discoveredFiles.Count == 0)
            return "not scanned";
        if (matches.Length == 0)
            return "0";

        var names = string.Join(", ", matches.Take(3).Select(file => $"`{file.RelativePath}` ({FormatBytes(file.Length)})"));
        return matches.Length <= 3 ? names : $"{matches.Length} files; {names}, …";
    }

    private static string FormatRanges(IReadOnlyList<ByteRange> ranges) => ranges.Count == 0
        ? "none"
        : string.Join(", ", ranges.Select(range => range.Length == 1
            ? $"`0x{range.Offset:X}`"
            : $"`0x{range.Offset:X}–0x{range.End:X}` ({range.Length} bytes)"));

    private static string FormatBytes(long bytes) => bytes < 1024
        ? $"{bytes} B"
        : bytes < 1024 * 1024
            ? $"{bytes / 1024d:0.0} KiB"
            : $"{bytes / (1024d * 1024d):0.0} MiB";

    private static string Percent(int known, int total) => total == 0
        ? "0.0%"
        : $"{known * 100d / total:0.0}%";

    private static string Escape(string value) => value.Replace("|", "\\|", StringComparison.Ordinal)
        .Replace("\r", " ", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);

    private static string Anchor(LayoutCoverage layout) => layout.TypeName
        .ToLowerInvariant().Replace('.', '-').Replace('+', '-');
}
