// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x8)]
public readonly struct SacredExecutableMonsterSpawnLayout
{
    [FieldOffset(0x0)] public readonly uint @type;
    [FieldOffset(0x4)] public readonly uint @quote;
}
