// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x10)]
public readonly struct SacredExecutableSystemTimeLayout
{
    [FieldOffset(0x0)] public readonly ushort @wYear;
    [FieldOffset(0x2)] public readonly ushort @wMonth;
    [FieldOffset(0x4)] public readonly ushort @wDayOfWeek;
    [FieldOffset(0x6)] public readonly ushort @wDay;
    [FieldOffset(0x8)] public readonly ushort @wHour;
    [FieldOffset(0xA)] public readonly ushort @wMinute;
    [FieldOffset(0xC)] public readonly ushort @wSecond;
    [FieldOffset(0xE)] public readonly ushort @wMilliseconds;
}
