// <auto-generated />
// Serialized executable layout.

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native cObjectSounds::eObjectSounds; native enumerator names and values.</summary>
[Flags]
public enum SacredExecutableObjectSoundFlags : int
{
    OSF_RESERVED = 1,
}
