// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x20)]
public readonly struct SacredExecutableTextureSubLayout
{
    [FieldOffset(0x0)] public readonly uint @texture;
    [FieldOffset(0x4)] public readonly ushort @sizeX;
    [FieldOffset(0x6)] public readonly ushort @sizeY;
    [FieldOffset(0x8)] public readonly short @x;
    [FieldOffset(0xA)] public readonly short @y;
    [FieldOffset(0xC), BinaryUnknown] public readonly uint @reserved;
    [FieldOffset(0x10)] public readonly float @u;
    [FieldOffset(0x14)] public readonly float @v;
    [FieldOffset(0x18)] public readonly float @tu;
    [FieldOffset(0x1C)] public readonly float @tv;
}
