// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x100)]
public readonly struct SacredExecutableSectorEnvironmentLayout
{
    [FieldOffset(0x0)] public readonly uint @flags;
    [FieldOffset(0x4)] public readonly byte @environmentValid;
    [FieldOffset(0x5)] public readonly SacredExecutableArray4SacredExecutableSectorWeatherLayout @environment;
    [FieldOffset(0x75)] public readonly byte @animalsValid;
    [FieldOffset(0x76)] public readonly SacredExecutableArray4SacredExecutableAnimalSpawnLayout @animals;
    [FieldOffset(0x96)] public readonly ushort @animalMinNum;
    [FieldOffset(0x98)] public readonly ushort @animalMaxNum;
    [FieldOffset(0x9A), BinaryUnknown] public readonly SacredExecutableArray20Byte @unused1;
    [FieldOffset(0xAE)] public readonly byte @monsterValid;
    [FieldOffset(0xAF)] public readonly SacredExecutableArray4SacredExecutableMonsterSpawnLayout @monster;
    [FieldOffset(0xCF)] public readonly ushort @monsterMinNum;
    [FieldOffset(0xD1)] public readonly ushort @monsterMaxNum;
    [FieldOffset(0xD3)] public readonly ushort @monsterMinLevel;
    [FieldOffset(0xD5)] public readonly ushort @monsterMaxLevel;
    [FieldOffset(0xD7)] public readonly byte @region01;
    [FieldOffset(0xD8), BinaryUnknown] public readonly SacredExecutableArray23Byte @unused;
    [FieldOffset(0xEF)] public readonly uint @musicID;
    [FieldOffset(0xF3)] public readonly uint @osSoundProfile;
    [FieldOffset(0xF7)] public readonly byte @waterTypeA;
    [FieldOffset(0xF8)] public readonly byte @waterTypeB;
    [FieldOffset(0xF9), BinaryUnknown] public readonly SacredExecutableArray7Byte @reserved;
}
