// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x1C)]
public readonly struct SacredExecutableSectorWeatherLayout
{
    [FieldOffset(0x0)] public readonly ushort @type;
    [FieldOffset(0x2)] public readonly SacredExecutableArray2Uint @time;
    [FieldOffset(0xA)] public readonly SacredExecutableArray2Uint @duration;
    [FieldOffset(0x12)] public readonly SacredExecutableArray2Byte @intensity;
    [FieldOffset(0x14)] public readonly SacredExecutableArray2Uint @params;
}
