// <auto-generated />
// Serialized executable layout.

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native eDefTypes; native enumerator names and values.</summary>
public enum SacredExecutableDefinitionKind : int
{
    Def_Position = 0,
    Def_Num = 1,
    Def_PoolPos = 2,
    Def_PoolRgn = 3,
}
