// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x80)]
public readonly struct SacredExecutableItemDescriptorLayout
{
    [FieldOffset(0x0)] public readonly uint @flags;
    [FieldOffset(0x4)] public readonly uint @textureID;
    [FieldOffset(0x8)] public readonly uint @texture3D;
    [FieldOffset(0xC)] public readonly uint @argb;
    [FieldOffset(0x10)] public readonly uint @pakGfxID;
    [FieldOffset(0x14)] public readonly uint @blockRadius;
    [FieldOffset(0x18)] public readonly ushort @weaponEntry;
    [FieldOffset(0x1A)] public readonly ushort @creatureEntry;
    [FieldOffset(0x1C)] public readonly uint @bookText;
    [FieldOffset(0x20)] public readonly uint @resourceid;
    [FieldOffset(0x24)] public readonly uint @soundpf;
    [FieldOffset(0x28)] public readonly short @anchorX;
    [FieldOffset(0x2A)] public readonly short @anchorY;
    [FieldOffset(0x2C)] public readonly ushort @aniNum;
    [FieldOffset(0x2E)] public readonly byte @family;
    [FieldOffset(0x2F)] public readonly byte @layer;
    [FieldOffset(0x30)] public readonly byte @aniMsFrame;
    [FieldOffset(0x31)] public readonly byte @gfxFileID;
    [FieldOffset(0x32)] public readonly ushort @radius;
    [FieldOffset(0x34)] public readonly SacredExecutableArray3Byte @lwh3d;
    [FieldOffset(0x37)] public readonly SacredExecutableArray32Byte @sname;
    [FieldOffset(0x57)] public readonly float @angle3D;
    [FieldOffset(0x5B)] public readonly ushort @shadowSub;
    [FieldOffset(0x5D)] public readonly short @shadowOffsetX;
    [FieldOffset(0x5F)] public readonly short @shadowOffsetY;
    [FieldOffset(0x61)] public readonly SacredExecutableArray2Byte @bookEntry;
    [FieldOffset(0x63)] public readonly byte @shadowScheerung;
    [FieldOffset(0x64)] public readonly ushort @shadowSize;
    [FieldOffset(0x66)] public readonly uint @textureFX;
    [FieldOffset(0x6A)] public readonly ushort @upgradeItemType;
    [FieldOffset(0x6C)] public readonly ushort @upgradeFlags;
    [FieldOffset(0x6E)] public readonly byte @textureFX_ID;
    [FieldOffset(0x6F)] public readonly byte @goreType;
    [FieldOffset(0x70)] public readonly uint @modelID;
    [FieldOffset(0x74)] public readonly ushort @SwitchType;
    [FieldOffset(0x76), BinaryUnknown] public readonly SacredExecutableArray10Byte @reserved4;
}
