// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x40)]
public readonly struct SacredExecutableStaticObjectLayout
{
    [FieldOffset(0x0)] public readonly uint @self;
    [FieldOffset(0x4)] public readonly uint @type;
    [FieldOffset(0x8)] public readonly uint @flags;
    [FieldOffset(0xC)] public readonly SacredExecutableWorldPositionLayout @wpos;
    /// <summary>Native union: signed quality (low 16 bits), quantity or content (32 bits).</summary>
    [FieldOffset(0x17)] public readonly int @q;
    [FieldOffset(0x1B)] public readonly uint @container;
    [FieldOffset(0x1F)] public readonly uint @next_item;
    [FieldOffset(0x23)] public readonly short @anchorOffX;
    [FieldOffset(0x25)] public readonly short @anchorOffY;
    [FieldOffset(0x27)] public readonly uint @trigger;
    [FieldOffset(0x2B)] public readonly ushort @triggerState;
    [FieldOffset(0x2D)] public readonly byte @heightLevelID;
    [FieldOffset(0x2E)] public readonly byte @miniObjU;
    [FieldOffset(0x2F)] public readonly byte @miniObjV;
    [FieldOffset(0x30)] public readonly byte @miniObjS;
    [FieldOffset(0x31)] public readonly byte @miniTime;
    [FieldOffset(0x32)] public readonly byte @miniFrames;
    [FieldOffset(0x33)] public readonly byte @layer;
    [FieldOffset(0x34)] public readonly byte @triggerInit;
    [FieldOffset(0x35)] public readonly byte @fxVisibleStates;
    [FieldOffset(0x36), BinaryUnknown] public readonly byte @reserved1;
    [FieldOffset(0x37)] public readonly byte @brightness;
    [FieldOffset(0x38), BinaryUnknown] public readonly SacredExecutableArray8Byte @reserved;
}
