// <auto-generated />
using System.Runtime.CompilerServices;

namespace Sacred.Core.Executable.Layouts;

[InlineArray(10)] public struct SacredExecutableArray10Byte { private byte _first; }
[InlineArray(1)] public struct SacredExecutableArray1Uint { private uint _first; }
[InlineArray(20)] public struct SacredExecutableArray20Byte { private byte _first; }
[InlineArray(23)] public struct SacredExecutableArray23Byte { private byte _first; }
[InlineArray(2)] public struct SacredExecutableArray2Byte { private byte _first; }
[InlineArray(2)] public struct SacredExecutableArray2Uint { private uint _first; }
[InlineArray(32)] public struct SacredExecutableArray32Byte { private byte _first; }
[InlineArray(32)] public struct SacredExecutableArray32SacredExecutableFileChunkLayout { private SacredExecutableFileChunkLayout _first; }
[InlineArray(39)] public struct SacredExecutableArray39Byte { private byte _first; }
[InlineArray(3)] public struct SacredExecutableArray3Byte { private byte _first; }
[InlineArray(4)] public struct SacredExecutableArray4Byte { private byte _first; }
[InlineArray(4)] public struct SacredExecutableArray4SacredExecutableAnimalSpawnLayout { private SacredExecutableAnimalSpawnLayout _first; }
[InlineArray(4)] public struct SacredExecutableArray4SacredExecutableMonsterSpawnLayout { private SacredExecutableMonsterSpawnLayout _first; }
[InlineArray(4)] public struct SacredExecutableArray4SacredExecutableSectorWeatherLayout { private SacredExecutableSectorWeatherLayout _first; }
[InlineArray(64)] public struct SacredExecutableArray64Byte { private byte _first; }
[InlineArray(7)] public struct SacredExecutableArray7Byte { private byte _first; }
[InlineArray(8)] public struct SacredExecutableArray8Byte { private byte _first; }
[InlineArray(8)] public struct SacredExecutableArray8Int { private int _first; }
[InlineArray(8)] public struct SacredExecutableArray8Ushort { private ushort _first; }
