// <auto-generated />
// Serialized executable layout.

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native cEventWeather::__unnamed; native enumerator names and values.</summary>
public enum SacredExecutableWeatherEventKind : int
{
    WEATHER_NONE = 0,
    WEATHER_RESET = 1,
    WEATHER_RAIN = 2,
    WEATHER_FOG = 3,
    WEATHER_GROUNDFOG = 4,
    WEATHER_SNOW = 5,
    WEATHER_RESERVED = 6,
    WEATHER_QUAKE = 7,
    WEATHER_NIGHT = 8,
    WEATHER_FLASH_ONCE = 9,
    WEATHER_ENTERSECTOR = 10,
    WEATHER_EXITSECTOR = 11,
    WEATHER_STOMP = 12,
}
