// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x24)]
public readonly struct SacredExecutableHeightLevelLayout
{
    [FieldOffset(0x0)] public readonly int @x;
    [FieldOffset(0x4)] public readonly int @y;
    [FieldOffset(0x8)] public readonly short @w;
    [FieldOffset(0xA)] public readonly short @h;
    [FieldOffset(0xC)] public readonly SacredExecutableFileChunkLayout @data;
    [FieldOffset(0x18)] public readonly SacredExecutableFileChunkLayout @xdata;
}
