// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x50)]
public readonly struct SacredExecutableTextureEntryLayout
{
    [FieldOffset(0x0)] public readonly SacredExecutableArray32Byte @name;
    [FieldOffset(0x20)] public readonly ushort @width;
    [FieldOffset(0x22)] public readonly ushort @height;
    [FieldOffset(0x24)] public readonly byte @type;
    [FieldOffset(0x25)] public readonly uint @RLEsize;
    [FieldOffset(0x29), BinaryUnknown] public readonly SacredExecutableArray39Byte @reserved;
}
