// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x20)]
public readonly struct SacredExecutableWorldTileLayout
{
    [FieldOffset(0x0)] public readonly uint @patchid;
    [FieldOffset(0x4)] public readonly uint @sobj;
    [FieldOffset(0x8)] public readonly uint @wobj;
    [FieldOffset(0xC)] public readonly uint @tobj;
    [FieldOffset(0x10)] public readonly SacredExecutableArray4Byte @heightKch;
    [FieldOffset(0x14)] public readonly SacredExecutableArray4Byte @color;
    [FieldOffset(0x18)] public readonly SacredExecutableArray4Byte @heightCrt;
    [FieldOffset(0x1C)] public readonly byte @relX;
    [FieldOffset(0x1D)] public readonly byte @relY;
    [FieldOffset(0x1E)] public readonly byte @flags;
    [FieldOffset(0x1F)] public readonly byte @type;
}
