// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x10)]
public readonly struct SacredExecutableMixedGroupLayout
{
    [FieldOffset(0x0)] public readonly uint @numTextures;
    [FieldOffset(0x4)] public readonly short @x;
    [FieldOffset(0x6)] public readonly short @y;
    [FieldOffset(0x8)] public readonly short @sx;
    [FieldOffset(0xA)] public readonly short @sy;
    [FieldOffset(0xC), BinaryUnknown] public readonly SacredExecutableArray1Uint @reserved;
}
