// <auto-generated />
// Serialized executable layout.

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native cObjectSounds::eObjectSound; native enumerator names and values.</summary>
public enum SacredExecutableObjectSoundType : int
{
    OST_INVALID = 0,
    OST_SOUND = 1,
}
