// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x64)]
public readonly struct SacredExecutableDefinitionLayout
{
    [FieldOffset(0x0)] public readonly SacredExecutableDefinitionKind @type;
    [FieldOffset(0x4)] public readonly SacredExecutableArray64Byte @name;
    [FieldOffset(0x44)] public readonly SacredExecutableArray8Int @p;
}
