// <auto-generated />
// Serialized executable layout.

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native cSectorEnvironment::eEVF; native enumerator names and values.</summary>
[Flags]
public enum SacredExecutableEnvironmentSections : int
{
    EVF_WEATHER = 1,
    EVF_ANIMALS = 2,
    EVF_MONSTER = 4,
}
