// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0xB)]
public readonly struct SacredExecutableWorldPositionLayout
{
    [FieldOffset(0x0)] public readonly ushort @map;
    [FieldOffset(0x2)] public readonly int @x;
    [FieldOffset(0x6)] public readonly int @y;
    [FieldOffset(0xA)] public readonly byte @z;
}
