// <auto-generated />
// Serialized executable layout.
using System.Runtime.InteropServices;
using Sacred.Core.Binary;

namespace Sacred.Core.Executable.Layouts;

/// <summary>Native executable layout. Version-specific: verify before applying names to Gold.</summary>
[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 0x300)]
public readonly struct SacredExecutableSectorChunkExLayout
{
    [FieldOffset(0x0)] public readonly SacredExecutableArray32Byte @sectorName;
    [FieldOffset(0x20)] public readonly uint @clientID;
    [FieldOffset(0x24)] public readonly uint @serverID;
    [FieldOffset(0x28)] public readonly uint @serverRevisionID;
    [FieldOffset(0x2C)] public readonly SacredExecutableArray8Ushort @surround;
    [FieldOffset(0x3C)] public readonly int @von_x;
    [FieldOffset(0x40)] public readonly int @von_y;
    [FieldOffset(0x44)] public readonly int @bis_x;
    [FieldOffset(0x48)] public readonly int @bis_y;
    [FieldOffset(0x4C)] public readonly SacredExecutableArray32SacredExecutableFileChunkLayout @lvlChunks;
    [FieldOffset(0x1CC)] public readonly uint @flags;
    [FieldOffset(0x1D0)] public readonly SacredExecutableArray2Uint @surround2;
    [FieldOffset(0x1D8)] public readonly byte @natureType;
    [FieldOffset(0x1D9)] public readonly SacredExecutableSystemTimeLayout @timeOfLastMod;
    [FieldOffset(0x1E9)] public readonly SacredExecutableSectorEnvironmentLayout @environment;
    [FieldOffset(0x2E9), BinaryUnknown] public readonly SacredExecutableArray23Byte @pad;
}
