<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWindowsForms>false</UseWindowsForms>

    <SingleFile>true</SingleFile>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <RootNamespace>SacredRemake</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <ProjectReference Include="..\Sacred.Engine\Sacred.Engine.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>

    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

    <Optimize>true</Optimize>
    <ReadyToRun>true</ReadyToRun>
    <ReadyToRunComposite>true</ReadyToRunComposite>
    <StripSymbols>true</StripSymbols>
    <Aot>true</Aot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StackTraceSupport>false</StackTraceSupport>
  </PropertyGroup>
</Project>
