namespace Sacred.Shaders;

/// <summary>Stable names for the graphics pipelines supplied by the Sacred shader catalog.</summary>
public enum Dx12PipelineKind
{
    Terrain,
    TerrainLiquidCover,
    ShadowOverlay,
    StaticSpriteShadow,
    StaticSprite,
    TransparentStaticSprite,
    PostModelTransparentStaticSprite,
    UnlitStaticSprite,
    TransparentUnlitStaticSprite,
    PostModelTransparentUnlitStaticSprite,
    TransparentUnlitParticleRgb,
    TransparentUnlitParticleArgb,
    TransparentUnlitParticleAlphaMask,
    DepthStaticSprite,
    DepthTransparentStaticSprite,
    DepthUnlitStaticSprite,
    DepthTransparentUnlitStaticSprite,
    LiquidSprite,
    SurfaceLightMap,
    PlayerOcclusionMap,
    LightHalo,
    StaticModel,
    ModelShadow,
    GroundShadow,
    TransparentModel,
    AnimatedModel,
    EffectModel,
    TransparentEffectModel,
    TransparentItemParticle,
    DenseItemParticle,
    ItemGlow,
    ItemParticleRgb,
    ItemParticleArgb,
    ItemParticleAlphaMask,
    ItemGlowRgb,
    ItemGlowArgb,
    ItemGlowAlphaMask,
    InventoryUi,
    ImGui,
    SolidModel,
    FxParticle
}
