<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raffinert.EmbeddedResourceAccessGenerator" Version="1.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>build; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyMetadata Include="SacredShadersBuildOutput" Value="$(TargetDir)" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shaders\*.hlsl" />
  </ItemGroup>

</Project>
