<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <Optimize>false</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
        <Optimize>true</Optimize>

        <SingleFile>true</SingleFile>
        <SelfContained>true</SelfContained>
        <Aot>true</Aot>
        <PublishAot>true</PublishAot>
        <PublishTrimmed>true</PublishTrimmed>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.17">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="Raffinert.EmbeddedResourceAccessGenerator" Version="1.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Vortice.Direct3D12" Version="3.8.3"/>
        <PackageReference Include="Vortice.DXGI" Version="3.8.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SacredItemSimulator\SacredItemSimulator.csproj"/>
        <ProjectReference Include="..\Sacred.Assets\Sacred.Assets.csproj"/>
        <ProjectReference Include="..\Sacred.Granny\Sacred.Granny.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Shaders\*.hlsl"/>
    </ItemGroup>
</Project>

