<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sacred.Core\Sacred.Core.csproj" />
    <ProjectReference Include="..\Sacred.Assets\Sacred.Assets.csproj" />
    <ProjectReference Include="..\Sacred.Inventory\Sacred.Inventory.csproj" />
  </ItemGroup>
</Project>
