<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sacred.Core\Sacred.Core.csproj" />
      <ProjectReference Include="..\Sacred.Granny\Sacred.Granny.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="World\Sectors\" />
      <Folder Include="World\Triggers\" />
    </ItemGroup>

</Project>
